### ISSUE TITLE
type.h big customized datatypes, allowing to processing large datatypes

### ISSUE THREAD

**Issue by divakareddy** [objectcomputing/liquibook#1]
Currently liquibook is unable to handle processing large datatypes which are greater than 64-bit values.
It would be great if code allows user to define customized datatypes in order to handle process bigger values under liquibook/src/book/type.h

for example:
instead of

  typedef uint32_t Price;
  typedef uint32_t Quantity;
  typedef uint32_t Cost;

User wants to define something similar to:
# include "uint128.h"

  typedef uint128_t Price;
  typedef uint128_t Quantity;
  typedef uint128_t Cost;

**Comment by dale-wilson** [comment]
Closing.  However I would be interested in what market place has prices and/or currency values larger than  9,223,372,036,854,775,807.  That would be 2 million times larger than the annual US budget (expressed in dollars).
