### ISSUE TITLE
errors when trying to build on windows

### ISSUE THREAD

**Issue by drormik** [objectcomputing/liquibook#2]
Hi!

question I was hoping someone knowledgeable could assist when building liquibook on windows 7 (64 bit)

I'm trying to build on windows using the command:

mwc.pl -type vc10 liquibook.mwc

for some reason i'm getting the error below about QuickFASTApplication, and depth_feed_publisher,mpc (which does exist) :

c:\GitHub\liquibook>C:\ACE_wrappers\bin\mwc.pl -type vc10 liquibook.mwc
MPC_ROOT was set to C:\ACE_wrappers\MPC.
Using C:/ACE_wrappers/bin/MakeProjectCreator/config/MPC.cfg
CIAO_ROOT was used in the configuration file, but was not defined.
DANCE_ROOT was used in the configuration file, but was not defined.
Generating 'vc10' output using liquibook.mwc
WARNING: liquibook.mwc: Command line files specified in a workspace are ignored.

Skipping ut_order_book_shared_ptr (liquibook_unit.mpc), it requires boost.
depth_feed_publisher.mpc: line 2:
ERROR: Unable to locate parent: QuickFASTApplication
liquibook.mwc: line 5:
ERROR: Unable to process examples/depth_feed_publisher/depth_feed_publisher.mpc
ERROR: Unable to process: liquibook.mwc

What am I missing ?
do i need to download  quickfix.dll  / other ?

Many thanks
Dror

**Comment by 3y2y** [comment]
Yes, The document and build instructions are so scarce.

I meet the problem too but don't know how to fix it.

$ mwc.pl -type make liquibook.mwc
Generating 'make' output using liquibook.mwc
WARNING: liquibook.mwc: Command line files specified in a workspace are ignored.
Skipping ut_order_book_shared_ptr (liquibook_unit.mpc), it requires boost.
depth_feed_publisher.mpc: line 2:
ERROR: Unable to locate parent: QuickFASTApplication
liquibook.mwc: line 5:
ERROR: Unable to process examples/depth_feed_publisher/depth_feed_publisher.mpc
ERROR: Unable to process: liquibook.mwc
