### ISSUE TITLE
error: no member named 'emplace' , when compiling Liquibook using make all

### ISSUE THREAD

**Issue by 7ur7Le** [objectcomputing/liquibook#20]
![screen shot 2018-06-23 at 7 16 40 pm](https://user-images.githubusercontent.com/26501778/41810314-23c258d2-771a-11e8-8608-c2b21f5917f2.png)
![screen shot 2018-06-23 at 7 17 02 pm](https://user-images.githubusercontent.com/26501778/41810316-2545f24a-771a-11e8-8002-255c2bc310bf.png)

**Comment by mitza-oci** [comment]
https://github.com/objectcomputing/liquibook#for-any-platform

C++11 is required
