### ISSUE TITLE
Unable to cancel stop order if it has not been triggered

### ISSUE THREAD

**Issue by Gordon-TheTurtle** [objectcomputing/liquibook#25]
OrderBook<OrderPtr>::cancel(const OrderPtr& order) function does not check for the order in stop orders during cancellation.
So if you place a cancel order for stop order that has not been triggered yet you will not be able to cancel it and a cancel reject callback is generated.

Correct behaviour:
1) Try to cancel the order in normal orders.
2) If order exists, generate cancel callback, else check for the order in stop orders.
3) If order exists, generate cancel callback else cancel reject callback.

I can submit a pull request if required.

**Comment by enewhuis** [comment]
I have confirmed a similar bug and may have a fix to merge soon after some additional scrutiny.

**Comment by Gordon-TheTurtle** [comment]
Great, I will start working on it.

**Comment by Gordon-TheTurtle** [comment]
Hi @enewhuis,

[ PR ](https://github.com/objectcomputing/liquibook/pull/29) for the same has been created and tested.

**Comment by enewhuis** [comment]
merged
