### ISSUE TITLE
How to built in ubuntu 12.04?

### ISSUE THREAD

**Issue by EMRJ** [objectcomputing/liquibook#6]
when i run mwc.pl -type make liquibook.mwc gives mwc.pl: command not found

**Comment by dejlek** [comment]
Hi guys, webpage says MPC is open-source product but I can't find source.

**Comment by mitza-oci** [comment]
http://downloads.ociweb.com/MPC/

**Comment by dendisuhubdy** [comment]
I found this

user:liquibook user$ . env.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]

do you mean ./env.sh?

**Comment by dendisuhubdy** [comment]
user:liquibook user$ vi env.sh
user:liquibook dendisuhubdy$ cd /usr/local/boost
-bash: cd: /usr/local/boost: No such file or directory
dendisuhubdy:liquibook dendisuhubdy$ cd /usr/local/opt/boost
dendisuhubdy:boost dendisuhubdy$ ls
INSTALL_RECEIPT.json	include			lib
dendisuhubdy:boost dendisuhubdy$ cd ..
dendisuhubdy:opt dendisuhubdy$ export BOOST_ROOT="/usr/local/opt/boost"
dendisuhubdy:opt dendisuhubdy$ cd ~/Documents/workspace/bitwyre/liquibook/
dendisuhubdy:liquibook dendisuhubdy$ mwc.pl -type make liquibook.mwc
Generating 'make' output using liquibook.mwc
WARNING: liquibook.mwc: Command line files specified in a workspace are ignored.
Skipping ut_order_book_shared_ptr (liquibook_unit.mpc), it requires boost.
depth_feed_publisher.mpc: line 2:
ERROR: Unable to locate parent: QuickFASTApplication
liquibook.mwc: line 5:
ERROR: Unable to process examples/depth_feed_publisher/depth_feed_publisher.mpc
ERROR: Unable to process: liquibook.mwc
user:liquibook user$

**Comment by iamtheschmitzer** [comment]
-f is the canonicalize option of readlink - follows symlinks

you can probably change that line to

export LIQUIBOOK_ROOT=`pwd`

**Comment by dale-wilson** [comment]
Closing this with a note that the build process has been recently updated.  It still uses MPC but there's more help in the env.sh file that prepares the build.
