### ISSUE TITLE
Multithreaded scenario

### ISSUE THREAD

**Issue by geronimo22** [objectcomputing/liquibook#8]
Hello, I was wondering if you have done some performance testing of your book in a multithreaded scenario? For e.g. 1 thread per book, and a total of X threads writing to their respective books. 

I ask because I noticed you're stl collection and are relying on stl::allocator. With multiple threads hitting the team simultaneously, I wonder how will the performance change.

**Comment by dale-wilson** [comment]
> Hello, I was wondering if you have done some performance testing of your book in a multithreaded scenario? For e.g. 1 thread per book, and a total of X threads writing to their respective books.

No, we haven't tested in that environment. 

> I ask because I noticed you're stl collection and are relying on stl::allocator. With multiple threads hitting the team simultaneously, I wonder how will the performance change.

This is definitely something to look into in the future.  Thanks for your interest.
